### ISSUE TITLE
サンリオワールドスマッシュボールについて

### ISSUE THREAD

**Issue by Ziggomatic** [km1ab/sfc-dumper-py#1]
メルカリで購入させていただいたものです｡
オプションパーツ無し組み立て､Raspberry Pi OS (64-bit)でsfc-dumper.pyを動かしてみたのですが
下記のようにファイル名は読み取れるものの､0バイトのファイルを出力してしまいます｡
ソケット差し込む場所以外ではんだ付け必要な場所などございますでしょうか｡
大変恐れ入りますがご教授いただければと思います｡

-------------------------
Game Info (Title, etc...)
-------------------------
24: 0x0
23: 0x8
22: 0x0
21: 0x20
size: unknown
LoROM
SANRIO SMASH BALL!   
-------------------------

OK Bokujo
start_address = 0x8000

**Comment by km1ab** [comment]
ご連絡ありがとうございます。
結果を見る限りはんだ付けは問題なさそうです。
開発途中ですが、以下のブランチでお試しいただけますでしょうか。
https://github.com/km1ab/sfc-dumper-py/tree/dev_options
宜しくお願い致します。
```
usage: sfc_dumper.py [-h] [-o FILENAME] [-v [VERBOSE]] [-d [DEBUG]] [-g [GAMEINFO]]

options:
  -h, --help            show this help message and exit
  -o FILENAME, --filename FILENAME
  -v [VERBOSE], --verbose [VERBOSE]
  -d [DEBUG], --debug [DEBUG]
  -g [GAMEINFO], --gameinfo [GAMEINFO]
```

**Comment by Ziggomatic** [comment]
![スクリーンショット 2023-03-14 201647](https://user-images.githubusercontent.com/6114212/224985217-2158aa7d-3997-4732-894c-efa336e98096.png)

該当ブランチで､何度かカセット挿入し直したら無事ダンプできました！
丁寧にご対応ありがとうございます！
